const { chromium } = require('./pw');
const T = require('./common');
const ok = (c, m) => console.log((c ? 'OK   ' : 'FAIL ') + m);
(async () => { const b = await chromium.launch(); const p = await (await b.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto(T.URL); await p.waitForTimeout(300);
const st = () => p.evaluate(() => ({ pin: UI.pin && C.byId.get(UI.pin).m.name, hl: document.querySelector('#main').classList.contains('hl'), btn: $$('.mline .mline-edit').length, under: $$('.chip-edit').length, modal: !!$('.modal') }));
const pos = sel => p.evaluate(sel => { const c = document.querySelector(sel); c.scrollIntoView({ block: 'center' }); const r = c.getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; }, sel);
const id = await p.evaluate(() => C.ms.find(x => x.m.name === 'Projekt-Update 1').id);
let s1 = await pos(`.cal .chip.S[data-m="${id}"]`);
await p.mouse.click(s1[0], s1[1]); await p.waitForTimeout(150);
let s = await st();
ok(s.pin === 'Projekt-Update 1' && s.hl && s.btn >= 1 && s.under === 0 && !s.modal, 'Klick auf S hält fest, „Bearbeiten“ hinter den Zeilen der Terminliste (nicht unter der Markierung), kein Dialog ' + JSON.stringify(s));
await p.screenshot({ path: 'r12_pin_s.png' });
const i1 = await pos(`.cal .chip.I[data-m="${id}"]`);
await p.mouse.click(i1[0], i1[1]); await p.waitForTimeout(150);
s = await st(); ok(s.pin === 'Projekt-Update 1' && s.btn >= 1, 'Klick auf I: ebenso');
await p.click('.mline .mline-edit >> nth=0'); await p.waitForTimeout(150);
ok((await st()).modal, '„Bearbeiten“ öffnet den Dialog'); await p.click('.modal footer button:has-text("Abbrechen")'); await p.waitForTimeout(100);
await p.evaluate(() => { const hd = document.querySelector('.sec[data-sec="kal"] .sec-t'); hd.closest('.sec').querySelector('.legend-inline').click(); });
await p.mouse.click(1550, 110); await p.waitForTimeout(150);
s = await st(); ok(!s.pin && s.btn === 0, 'Klick woanders hebt auf ' + JSON.stringify(s));
const pp = await pos(`.cal .chip.P[data-m="${id}"]`);
await p.mouse.click(pp[0], pp[1]); await p.waitForTimeout(150);
s = await st(); ok(s.pin === 'Projekt-Update 1' && s.hl && s.btn >= 1 && !s.modal, 'Klick auf P hält ebenfalls fest, kein Dialog ' + JSON.stringify(s));
await p.screenshot({ path: 'r13_pin_p.png' });
await p.click('.mline .mline-edit >> nth=0'); await p.waitForTimeout(150);
ok((await st()).modal, '„Bearbeiten“ unter P öffnet den Dialog'); await p.click('.modal footer button:has-text("Abbrechen")'); await p.waitForTimeout(100);
await p.keyboard.press('Escape'); await p.waitForTimeout(100);
s = await st(); ok(!s.pin && s.btn === 0, 'Esc hebt auf');
// P ziehen verschiebt weiterhin das Projekt
const pal0 = await p.evaluate(id => C.byId.get(id).pal, id);
const pp2 = await pos(`.cal .chip.P[data-m="${id}"]`);
const nx = await p.evaluate(([id, pal]) => { const c = document.querySelector('.day[data-dn="' + (pal + 2) + '"]'); const r = c.getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; }, [id, pal0]);
await p.mouse.move(pp2[0], pp2[1]); await p.mouse.down(); await p.mouse.move(pp2[0] + 10, pp2[1], { steps: 3 }); await p.mouse.move(nx[0], nx[1], { steps: 5 }); await p.mouse.up(); await p.waitForTimeout(150);
const pal1 = await p.evaluate(id => C.byId.get(id).pal, id);
ok(pal1 === pal0 + 2 && !(await st()).pin, 'P ziehen verschiebt weiterhin (+' + (pal1 - pal0) + ' Tage), ohne festzuhalten');
await p.evaluate(() => undo()); await p.waitForTimeout(100);
// zweifarbige Linie
const ln = await p.evaluate(id => { highlight(id); const x = C.byId.get(id); const g = n => { const c = document.querySelector('.day[data-dn="' + n + '"]'); return [c.style.getPropertyValue('--hcl'), c.style.getPropertyValue('--hcr')]; };
  const r = [g(x.s), g(x.s + 3), g(x.i), g(x.i + 3), g(x.pal)]; highlight(null); return [r, x.color]; }, id);
const [[s0, sMid, iDay, iMid, pDay], col] = ln;
ok(s0[0] === 'none' && sMid[0] === sMid[1] && sMid[0] !== iMid[0] && iDay[0] === sMid[0] && iDay[1] === iMid[0] && pDay[1] === 'none',
  'Linie: S→I heller (' + sMid[0] + '), I→PAL kräftig (' + iMid[0] + '), Wechsel genau am I-Tag');
await p.evaluate(() => { UI.verbund = true; renderNow(); });
const vb = await p.evaluate(id => { const x = C.byId.get(id); const v = n => { const e = document.querySelector('.day[data-dn="' + n + '"] .vbl[data-m="' + id + '"]'); return e && [e.style.getPropertyValue('--hcl'), e.style.getPropertyValue('--hcr')]; }; return [v(x.s + 3), v(x.i + 3)]; }, id);
ok(vb[0] && vb[1] && vb[0][0] !== vb[1][0], 'Verbund-Darstellung ebenfalls zweifarbig ' + JSON.stringify(vb));
await p.evaluate(() => { const s = document.querySelector('.sec[data-sec="kal"]'); document.querySelector('#main').scrollTop = s.offsetTop - 50; });
await p.screenshot({ path: 'r12_verbund.png' });
await p.evaluate(() => { UI.verbund = false; renderNow(); });
const hs = await p.evaluate(id => { highlight(id); return 1; }, id);
await p.evaluate(() => { const s = document.querySelector('.sec[data-sec="kal"]'); document.querySelector('#main').scrollTop = s.offsetTop - 50; });
await p.screenshot({ path: 'r12_hover_line.png' });
// Startbildschirm-Logo
await p.evaluate(() => { highlight(null); window.__splashTest = true; showSplash(); }); await p.waitForTimeout(300);
const lh = await p.evaluate(() => Math.round(document.querySelector('.splash-logo').getBoundingClientRect().height));
ok(lh === 51, 'Logo auf dem Startbildschirm ' + lh + ' px hoch (vorher 34)');
await p.waitForTimeout(1800); await p.screenshot({ path: 'r12_splash.png' });
console.log('ERR', errs.join('|') || 'keine'); await b.close(); })();
